### ISSUE TITLE
Notify url not called

### ISSUE THREAD

**Issue by AkashDesai52** [louislewis2/payfast#15]
i am implementing this project in .net core.

After i paid a payment notify url is not called.
it directly open success page.
i want to get response in notify url.

please help me for this.

here i attached a video link for not calling notify action
[https://www.screencast.com/t/QNPUcorwY]

**Comment by louislewis2** [comment]
Hi, Thanks for reaching out.

There is no real success page in the sample. I do have a return page. They imply very different meanings. 

Please see this great bit of documentation from PayFast.
https://developers.payfast.co.za/documentation/#notify-page-itn

For the return page documentation
https://developers.payfast.co.za/documentation/#success-page

The return page does not have anything to do whether the transaction has actually completed
successfully. The notify url is called when the transaction is complete. This can happen at different times, which is why in the sample application the return page, does not say thank you, we have received your money, instead it mentions that the payment is being processed as this reflects what is happening in reality. You should also double check the passphrase, the values must match, otherwise this can also cause ITN related errors.

Further, you cannot use a local url for ITN callbacks, the link must be a publicly available, otherwise their servers would not be able to reach your endpoint.

In the sandbox, there is a tool you can use to help track what it happening with the ITN call.
Please see their documentation for this tool, at the link below.

https://developers.payfast.co.za/documentation/#sandbox-tools

Further troubleshooting guidance can be found here

https://support.payfast.co.za/article/42-why-am-i-not-receiving-the-itn-callback
https://developers.payfast.co.za/documentation/#i-do-not-receive-the-itn-callback-why 
https://developers.payfast.co.za/documentation/#the-supplied-variable-are-not-according-to-specification

Hope this helps.
