### ISSUE TITLE
issue(ITN signature): Not valid on sub cancel or charged

### ISSUE THREAD

**Issue by dylanvdmerwe** [louislewis2/payfast#3]
Thanks for this awesome sample!

After starting a subscription, the ITN is called and the signature check is valid.

However, from the sandbox test console, charging a subscription again (to simulate the next payment) or calling cancel, the signature check does not pass. 
![image](https://cloud.githubusercontent.com/assets/2852839/26374578/0ee0ac94-4006-11e7-8ef4-0b5cc488f8c2.png)

The only difference seems to be that the `billing_date` field is null.

Example charge JSON:
```
{"m_payment_id":"22be80e7-5ffc-4344-8318-4932fc5ad8c1","pf_payment_id":"358188","payment_status":"COMPLETE","item_name":"Estate 86 - Small","item_description":"Estate 86 Small Tier - R699.00 per month. Up to 150 residents allowed.","amount_gross":"699.00","amount_fee":"-33.36","amount_net":"665.64","custom_str1":null,"custom_str2":null,"custom_str3":null,"custom_str4":null,"custom_str5":null,"custom_int1":null,"custom_int2":null,"custom_int3":null,"custom_int4":null,"custom_int5":null,"name_first":"Test","name_last":"User 01","email_address":"sbtu01@payfast.co.za","merchant_id":"10004877","token":"d69f1762-0979-e4a0-5d1c-d9ea2f87ff39","billing_date":null,"signature":"e536bb763875380b83f17a9db3b7e9d3"}
```

Example cancel JSON:
```
{"m_payment_id":"c0fb04ae-b41f-43d2-b073-12c7a9fae8c1","pf_payment_id":"357363","payment_status":"CANCELLED","item_name":"Estate 86 - Small","item_description":"Estate 86 Small Tier - R699.00 per month. Up to 150 residents allowed.","amount_gross":null,"amount_fee":null,"amount_net":null,"custom_str1":null,"custom_str2":null,"custom_str3":null,"custom_str4":null,"custom_str5":null,"custom_int1":null,"custom_int2":null,"custom_int3":null,"custom_int4":null,"custom_int5":null,"name_first":"Test","name_last":"User 01","email_address":"sbtu01@payfast.co.za","merchant_id":"10004877","token":"fc57748f-033d-6328-6962-53717289f8fd","billing_date":null,"signature":"8a0221a51c7ebd11070d44f965f2c87e"}
```

Not entirely sure why the signature would not work, as you do have a check for `billing_date` being null in the hash check.

**Comment by louislewis2** [comment]
Hi @dylanvdmerwe 

Sorry for the delay, just been quite busy on this side. I will get this tested on my side and see if I can duplicate the issue and then revert back to you. Are you using the default test / sandbox credentials?

**Comment by dylanvdmerwe** [comment]
No worries. I was using standard sandbox credentials yes.

**Comment by louislewis2** [comment]
Hi @dylanvdmerwe I sat this evening with your issue. I was able to repro it.
I am escalating it to the guys at Payfast. I will let you know the feedback as soon as I get it.

**Comment by louislewis2** [comment]
Hi @dylanvdmerwe I have found this issue that you mentioned above.
I will have to take it up with Payfast themselves. The problem is the position of the token variable. When you do a charge, it is the second variable when you initially create it, it is second last, next to the signature. 

The order of the variables are of course critical, the strange part is that the order I place each of the variables onto the class I got of their documentation. If I move it to the second position, then your error goes away, but then the initial request is wrong. 

If this is not a issue on their side, I will need to create a special routine to check the incoming parameter positions and then pass that into the routine that generates the signature to order them correctly.

Lastly sorry for the delay, It has been tough to find time.

Another issue was reported today https://github.com/louislewis2/payfast/issues/4 which I was able to sort out. So a new package will soon be on the way, I just want to hear from Payfast and get your fix in as well before I release.

**Comment by louislewis2** [comment]
This issue has been fixed. The processing of the itn is slightly more complicated than originally implemented, primarily due to misunderstanding the documentation on their site regarding order of variables and so on.

Please check the new samples, there are now two. One for Asp.Net Mvc and the other Asp.Net Core. You will need to use either of the related packages. The readme has been updated with the relevant details. Each of the sample use a different library which assists with the itn postback.

Thanks for providing your feedback, again apologies for the long turn around time.
