### ISSUE TITLE
Signature not calculated correctly when passphrase is not set

### ISSUE THREAD

**Issue by damiennorth** [louislewis2/payfast#4]
Using the test credentials specified in the PayFast documentation and creating a PayFastRequest using no passphrase (or an empty string as a passphrase) returns an invalid signature ("Generated signature does not match submitted signature"). Note that I can generate a valid signature in PHP with the exact same parameters.

Using the credentials from your unit test with the given passphrase works correctly.

**Comment by louislewis2** [comment]
Hi @damiennorth Thanks for reporting the issue. I was to reproduce it with ease and track down the issue. I have also found the cause of the other reported issue. I am going to check in with Payfast tomorrow to see if we can solve it with them, otherwise I will write the workaround I mentioned. So a new package will be available soon. I will let you know when it ready.

**Comment by louislewis2** [comment]
Hi there, issue has been fixed. Please see the readme for the updates. New packages have been deployed as well. Thanks for reporting the issue. It all helps.

**Comment by damiennorth** [comment]
Thank you so much for the fast reply @louislewis2 and for releasing a fix so quickly. Excellent library by the way, saved us a lot of time.

**Comment by louislewis2** [comment]
Thanks a lot, happy to hear. 👍
