### ISSUE TITLE
Signature hash fails with foreign characters

### ISSUE THREAD

**Issue by damiennorth** [louislewis2/payfast#5]
Hi,

Sorry to raise another issue with this but while testing we noticed that passing 'foreign' UTF-8 characters in parameter values resulted in an invalid signature. This seems to be because the CreateHash method uses Encoding.ASCII.GetBytes instead of setting encoding to UTF-8.

Currently having a word like 'México' as a parameter value will lead to an invalid signature hash.

Thanks in advance for taking the time to resolve this.

Best wishes,

Damien

**Comment by louislewis2** [comment]
@damiennorth Thanks for bringing this up, I would never have entered those as test characters.
I will push a fix through for this tonight after work.

**Comment by damiennorth** [comment]
Hi Louis,

I was actually about to test a fix and then submit it as a pull request,
might save you the hassle :)

Best wishes,

D

**Comment by louislewis2** [comment]
That would be awesome, I'll accept a pull request if you are already going down that path.

**Comment by louislewis2** [comment]
Sorry I have not got to this yet. I do believe your update is closer to the truth.
The standard .NET implementation differs from PHP as one might expect, that is why I opted for a more manual method as you discovered :)

I will do my best to make time soonest for you just to test as best I can before rolling out the updated package. Thanks for the fiddle as well, it does help a lot.

I am well aware of this method that you used (System.Net.WebUtility.UrlEncode)
The problem with that method, was that when I initial started writing the library using that method under circumstances encoded various values differently than php, this meant that when Payfast generates the hash and does the security check it fails due to a signature mismatch. 

I need to run through the initial samples that I was using when I started this library and find the scenarios that break and will then drop them over here. Testing with a single string as you did in the fiddle, helps but does not show the full story. You need to run all variables through it (Full GET string) and then compare them to php generated values. I will also add this to the wiki just for future reference.

Run your fiddle using my "bad encode function" as well as your method using this get string.
```
merchant_id=10004241&merchant_key=132ncgdwrh2by&return_url=https://www.coolsite.azure.com/return&cancel_url=https://www.coolsite.azure.com/return&notify_url=https://coolsite.azure.com/process&name_first=John&name_last=Smith&email_address=john@smith.com&amount=12.35&item_name=Cool item&item_description=awesome description&custom_int1=8&custom_str1=test_string&custom_str2=Happiness!Maybe?Semi;
```

PHP generates this as a result for me.

```
merchant_id%3D10004241%26merchant_key%3D132ncgdwrh2by%26return_url%3Dhttps%3A%2F%2Fwww.coolsite.azure.com%2Freturn%26cancel_url%3Dhttps%3A%2F%2Fwww.coolsite.azure.com%2Freturn%26notify_url%3Dhttps%3A%2F%2Fcoolsite.azure.com%2Fprocess%26name_first%3DJohn%26name_last%3DSmith%26email_address%3Djohn%40smith.com%26amount%3D12.35%26item_name%3DCool+item%26item_description%3Dawesome+description%26custom_int1%3D8%26custom_str1%3Dtest_string%26custom_str2%3DHappiness%21Maybe%3FSemi%3B
```

This is a quick example I made, there are a few characters though that would differ between WebUtility and PHP's method. The regex I have in place fixes further issues that are caused in certain scenarios.

**Comment by damiennorth** [comment]
Sorry I was away on holiday last week. It looks like your PHP code is encoding the whole string instead of encoding each parameter, or doing some sort of double encoding. My PHP script (taken from PayFast documentation) creates a valid URL that looks like this: 

https://sandbox.payfast.co.za/eng/process?merchant_id=10000100&merchant_key=46f0cd694581a&return_url=https%3A%2F%2F5ca4377c.ngrok.io%2Fhome%2Freturn&cancel_url=https%3A%2F%2F5ca4377c.ngrok.io%2Fhome%2Fcancel&notify_url=https%3A%2F%2F5ca4377c.ngrok.io%2Fhome%2Fnotify&email_address=sbtu01%40payfast.co.za&m_payment_id=8d00bf49-e979-4004-228c-08d452b86380&amount=30&item_name=Foreign+%C3%87h%C3%A5ract%C3%A9rs&item_description=Some+details+about+the+once+off+payment&signature=c83013dd7ff3e7c4b0917b2af6e4bfcc

where only the parameter values have been URL encoded. I'll run some more tests with full PayFast parameters and see if I can figure out the PHP/.NET differences.

**Comment by damiennorth** [comment]
Hi, I've run further tests with my changes and it actually works correctly EXCEPT where the parameters contain parentheses (which was the case in my previous tests). This is because .NET URLEncode (rightfully) doesn't encode some characters, following the proper recommendations, whereas JS and PHP implementations do. See https://msdn.microsoft.com/en-us/library/system.net.webutility.urlencode(v=vs.110).aspx#Anchor_1. I'll try to see if there's an easy way around it, else we might have to manually force encoding for these characters.

**Comment by damiennorth** [comment]
I've updated my branch (see pull request) with a manual fix for the three characters that seem to be missed out by URLEncode: `()!`.

The few tests I've ran have generated valid PayFast URLs (valid signature).

**Comment by louislewis2** [comment]
@damiennorth Howzit, sorry for the delay. It has been an extremely busy 2 weeks for me.
I have not had a moment to test this yet, so I am just going ask if you have tested it on your end?
If so, I will just accept the merge and get new packages out. Let me know.

**Comment by damiennorth** [comment]
Hi Louis, Unfortunately I haven't fully tested the changes. I've tested
them with our own implementation of the library which uses some but not all
of the functionalities. I couldn't get the unit tests to load in my
solution so I couldn't run those either. I would recommend at least getting
the unit tests to pass successfully (for regression testing) before
releasing the packages. Thanks again for your help.
